name: Java Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Check out code
      uses: actions/checkout@v2

    - name: List contents
      run: |
        ls
        ls javatest/

    - name: Compile and Run Java Files
      run: |
        javac javatest/FileCopyExample.java
        java -cp $GITHUB_WORKSPACE/javatest FileCopyExample
      shell: bash
