name: Java Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Compile and Run Java Files
      run: |
        cd JavaSE-49.java.io/JavaSE-49.java.io/JavaSE-49.java.io/javatest/
        javac FileCopyExample.java
        java FileCopyExample
      shell: bash
