name: Java Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Compile and Run Java Files
      run: |
        javac FileExample.java
        java FileExample
      shell: bash

    - name: Debug
      run: |
        ls -R # List all files in the current directory and subdirectories
        ls -R javatest # List all files in the specific directory
      shell: bash
