name: Java Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Check out code
      uses: actions/checkout@v2

    - name: List files in the current directory
      run: ls -R $GITHUB_WORKSPACE

    - name: Navigate to javatest directory
      run: cd $GITHUB_WORKSPACE/path/to/javatest

    - name: Compile and Run Java Files
      run: |
        javac FileExample.java
        java FileExample
      shell: bash
